# LinearRegression from Scratch


# 구현할 것
- 공부시간과 성적간의 관계를 모델링한다.
    - **머신러닝 모델(모형)이란** 수집한 데이터를 기반으로 입력값(Feature)와 출력값(Target)간의 관계를 하나의 공식으로 정의한 함수이다. 그 공식을 찾는 과정을 **모델링**이라고 한다.
    - 이 예제에서는 공부한 시험시간으로 점수를 예측하는 모델을 정의한다.
    - 입력값과 출력값 간의 관계를 정의할 수있는 다양한 함수(공식)이 있다. 여기에서는 딥러닝과 관계가 있는 **Linear Regression** 을 사용해본다.

# 데이터 확인
- 입력데이터: 공부시간
- 출력데이터: 성적

|공부시간|점수|
|-|-|
|1|20|
|2|40|
|3|60|

우리가 수집한 공부시간과 점수 데이터를 바탕으로 둘 간의 관계를 식으로 정의 할 수 있으면 **내가 몇시간 공부하면 점수를 얼마 받을 수 있는지 예측할 수 있게 된다.**   
수집한 데이터를 기반으로 앞으로 예측할 수있는 모형을 만드는 것이 머신러닝 모델링이다.

  

## 학습(훈련) 데이터셋 만들기
- 모델을 학습시키기 위한 데이터셋을 구성한다.
- 입력데이터와 출력데이터을 각각 다른 행렬로 구성한다.
- 하나의 데이터 포인트의 입력/출력 값은 같은 index에 정의한다.

### 선형회귀 (Linear Regression)
- Feature들의 가중합을 이용해 Target을 추정한다.
- Feature에 곱해지는 가중치(weight)들은 각 Feature가 Target 얼마나 영향을 주는지 영향도가 된다.
    - 음수일 경우는 target값을 줄이고 양수일 경우는 target값을 늘린다.
    - 가중치가 0에 가까울 수록 target에 영향을 주지 않는 feature이고 0에서 멀수록 target에 많은 영향을 준다.
- 모델 학습과정에서 가장 적절한 Feature의 가중치를 찾아야 한다.
      

\begin{align}
&\large \hat{y} = W\cdot X + b\\
&\small \hat{y}: \text{모델추정값}\\
&\small W: \text{가중치}\\
&\small X: \text{Feature(입력값)}\\
&\small b: \text{bias(편향)}
\end{align}



## Train dataset 구성
- Train data는 feature(input)와 target(output) 각각 2개의 행렬로 구성한다.
- Feature의 행은 관측치(개별 데이터)를 열을 Feature(특성, 변수)를 표현한다. 이 문제에서는 `공부시간` 1개의 변수를 가진다.
- Target은 모델이 예측할 대상으로 행은 개별 관측치, 열은 각 항목에 대한 정답으로 구성한다.   
  이 문제에서 예측할 항목은 `시험점수` 한개이다.

In [6]:
import torch

X_train = torch.tensor([[1], [2], [3]], dtype=torch.float32)    # 공부시간
y_train = torch.tensor([[20], [40], [60]], dtype=torch.float32) # 시험점수
X_train.size(), y_train.size()

(torch.Size([3, 1]), torch.Size([3, 1]))

In [2]:
!uv pip install torch torchvision

Audited 2 packages in 8ms


In [ ]:
import torch

In [4]:
!uv pip uninstall torch torchvision

Uninstalled 2 packages in 2.07s
 - torch==2.9.1
 - torchvision==0.24.1


In [5]:
!uv pip install torch==2.8 torchvision

Resolved 13 packages in 65ms
Installed 2 packages in 2.61s
 + torch==2.8.0
 + torchvision==0.23.0


In [ ]:
a =[1,2,3]
a

## 파라미터 (weight, bias) 정의
- 학습대상/최적화 대상

In [7]:
import torch
weight = torch.randn(1, 1, requires_grad=True) # feature에 곱할 값. 
# 1 : (가중치) 위에서 feature가 한개이므로 숫자 1로 지정.
# 1 : 숫자 1로 지정
# 1 : 입력 feature 갯수,  1 : 출력값(예측 결과)의 갯수
bias = torch.randn(1, requires_grad=True)
print(weight.size(), bias.size())
print(weight)
print(bias)

torch.Size([1, 1]) torch.Size([1])
tensor([[0.0168]], requires_grad=True)
tensor([0.5387], requires_grad=True)


In [ ]:
#추론
pred = X_train @ weight + bias


In [ ]:
# 정답
y_train

tensor([[20.],
        [40.],
        [60.]])

In [ ]:
# 오차계산
loss = torch.mean((y_train - pred) ** 2, dim=0)
loss

tensor([1776.5629], grad_fn=<MeanBackward1>)

In [ ]:
# gradient 계산 -> loss에 대한 weight, bias의 순간변화율(gradient) 를 계산.
loss.backward()

In [ ]:
weight.grad, bias.grad

(tensor([[-182.1032]]), tensor([-77.8756]))

In [ ]:
lr = 0.1
weight.data = weight.data - weight.grad * lr
weight.data

NameError: name 'weight' is not defined

In [ ]:
bias.data = bias.data - bias.grad * lr
bias.data

tensor([8.3777])

### 모델링

In [ ]:
# 모델 정의
weight = torch.randn(1, 1, requires_grad=True)
bias = torch.randn(1, requires_grad=True)

# 추론 모델
def linear_model(X):
    return X @ weight + bias


In [ ]:
# loss(오차) 계산 함수
def mse_loss_fn(pred, y):
    return torch.mean((y-pred)**2)

### 학습
1. 모델을 이용해 추정한다.
   - pred = model(input)
1. loss를 계산한다.
   - loss = loss_fn(pred, target)
1. 계산된 loss를 파라미터에 대해 미분하여 계산한 gradient 값을 각 파라미터에 저장한다.
   - loss.backward()
1. optimizer를 이용해 파라미터를 update한다.
   - optimizer.step()  
1. 파라미터의 gradient(미분값)을 0으로 초기화한다.
   - optimizer.zero_grad()
- 위의 단계를 반복한다.   

위 1~4 : 1 step

In [ ]:
epochs = 2000 # train set을 몇번 학습(파라미터 업데이트)시킬지.
lr = 0.01 #learning rate
for epoch in range(epochs):
    #1. 추론(예측)
    pred = linear_model(X_train)
    #2.오차계산
    loss = mse_loss_fn(pred, y_train)
    #3. 파라미터들(weight, bias)에 대한 gradient 계산
    loss.backward()
    #4. 파라미터 업데이트
    weight.data = weight.data - lr * weight.grad
    bias.data = bias.data - lr * bias.grad
    if epoch == epochs-1:
        print("last:", weight.grad, bias.grad)
    #5. gradient 초기화
    weight.grad = None
    bias.grad = None
    # 100 epoch마다 loss를 출력
    if epoch % 100 == 0 or epoch == epochs-1:
        print(f"[{epoch}/{epochs}] - loss: {loss.item():.4f}")

[0/2000] - loss: 1596.5850
[100/2000] - loss: 5.0854
[200/2000] - loss: 3.1425
[300/2000] - loss: 1.9418
[400/2000] - loss: 1.1999
[500/2000] - loss: 0.7415
[600/2000] - loss: 0.4582
[700/2000] - loss: 0.2831
[800/2000] - loss: 0.1750
[900/2000] - loss: 0.1081
[1000/2000] - loss: 0.0668
[1100/2000] - loss: 0.0413
[1200/2000] - loss: 0.0255
[1300/2000] - loss: 0.0158
[1400/2000] - loss: 0.0097
[1500/2000] - loss: 0.0060
[1600/2000] - loss: 0.0037
[1700/2000] - loss: 0.0023
[1800/2000] - loss: 0.0014
[1900/2000] - loss: 0.0009
last: tensor([[-0.0065]]) tensor([0.0148])
[1999/2000] - loss: 0.0005


In [ ]:
weight.data, bias.data

(tensor([[19.9707]]), tensor([0.0666]))

In [ ]:
# 추론
# gradient 함수를 구하지 않는다.
with torch.no_grad():
    new_X = torch.tensor([[5], [7]], dtype=torch.float32)
    pred = linear_model(new_X)
    print(pred)

tensor([[ 99.9262],
        [139.8721]])


# 다중 입력, 다중 출력
- 다중입력: Feature가 여러개인 경우
- 다중출력: Output 결과가 여러개인 경우

다음 가상 데이터를 이용해 사과와 오렌지 수확량을 예측하는 선형회귀 모델을 정의한다.  
[참조](https://www.kaggle.com/code/aakashns/pytorch-basics-linear-regression-from-scratch)


|온도(F)|강수량(mm)|습도(%)|사과생산량(ton)|오렌지생산량|
|-|-|-|-:|-:|
|73|67|43|56|70|
|91|88|64|81|101|
|87|134|58|119|133|
|102|43|37|22|37|
|69|96|70|103|119|

```
사과수확량  = w11 * 온도 + w12 * 강수량 + w13 * 습도 + b1
오렌지수확량 = w21 * 온도 + w22 * 강수량 + w23 *습도 + b2
```

- `온도`, `강수량`, `습도` 값이 **사과**와, **오렌지 수확량**에 어느정도 영향을 주는지 가중치를 찾는다.
    - 모델은 사과의 수확량, 오렌지의 수확량 **두개의 예측결과를 출력**해야 한다.
    - 사과에 대해 예측하기 위한 weight 3개와 오렌지에 대해 예측하기 위한 weight 3개 이렇게 두 묶음, 총 6개의 weight를 정의하고 학습을 통해 가장 적당한 값을 찾는다.
        - `개별 과일를 예측하기 위한 weight들 @ feature들` 의 계산 결과를  **Node, Unit, Neuron** 이라고 한다.
        - 두 과일에 대한 Unit들을 묶어서 **Layer** 라고 한다.
- 목적은 우리가 수집한 train 데이터셋을 이용해 **정확한 예측을 위한 weight와 bias 들**을 찾는 것이다.

## Train Dataset
- Train data는 feature(input)와 target(output) 각각 2개의 행렬로 구성한다.
- Feature의 행은 관측치(개별 데이터)를 열을 Feature(특성, 변수)를 표현한다. 이 문제에서는 `온도, 강수량, 습도` 세개의 변수를 가진다.
- Target은 모델이 예측할 대상으로 행은 개별 관측치, 열은 각 항목에 대한 정답으로 구성한다. 이 문제에서 예측할 항목은 `사과수확량, 오렌지 수확량` 2개의 값이다.

In [8]:
#  input: 생산환경 (temp, rainfall, humidity) : (5, 3)
environs = [
    [73, 67, 43], 
    [91, 88, 64], 
    [87, 134, 58], 
    [102, 43, 37], 
    [69, 96, 70]
]

# Targets: 생산량 - (apples, oranges) - (5, 2)
apple_orange_output = [
    [56, 70], 
    [81, 101], 
    [119, 133], 
    [22, 37], 
    [103, 119]
]

In [9]:
import torch
# Dataset을 torch.Tensor로 생성
X = torch.tensor(environs, dtype=torch.float32)
y = torch.tensor(apple_orange_output, dtype=torch.float32)
X.shape, y.shape

(torch.Size([5, 3]), torch.Size([5, 2]))

In [ ]:
!uv pip install torch torchvision

Resolved 13 packages in 48ms
Prepared 1 package in 556ms
Installed 13 packages in 3.90s
 + filelock==3.20.0
 + fsspec==2025.10.0
 + jinja2==3.1.6
 + markupsafe==3.0.3
 + mpmath==1.3.0
 + networkx==3.5
 + numpy==2.3.5
 + pillow==12.0.0
 + setuptools==80.9.0
 + sympy==1.14.0
 + torch==2.9.1
 + torchvision==0.24.1
 + typing-extensions==4.15.0


In [ ]:
X

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

## weight와 bias
- weight: 각 feature들이 생산량에 영향을 주었는지의 가중치로 feature에 곱해줄 값.
    - 사과, 오렌지의 생산량을 구해야 하므로 가중치가 두개가 된다.
    - weight의 shape: `(3, 2)`
- bias는 모든 feature들이 0일때 생산량이 얼마일지를 나타내는 값으로 feature와 weight간의 가중합 결과에 더해줄 값이다.
    - 사과, 오렌지의 생산량을 구하므로 bias가 두개가 된다.
    - bias의 shape: `(2, )`

### Linear Regression model
모델은 weights `w`와 inputs `x`의 내적(dot product)한 값에 bias `b`를 더하는 함수.

$$
\hspace{2.5cm} X \hspace{1.1cm} \cdot \hspace{1.2cm} W \hspace{1.2cm}  + \hspace{1cm} b \hspace{2cm}
$$

$$
\left[ \begin{array}{cc}
73 & 67 & 43 \\
91 & 88 & 64 \\
\vdots & \vdots & \vdots \\
69 & 96 & 70
\end{array} \right]
%
\cdot
%
\left[ \begin{array}{cc}
w_{11} & w_{21} \\
w_{12} & w_{22} \\
w_{13} & w_{23}
\end{array} \right]
%
+
%
\left[ \begin{array}{cc}
b_{1} & b_{2} \\
b_{1} & b_{2} \\
\vdots & \vdots \\
b_{1} & b_{2} \\
\end{array} \right]
$$


$w_{11},\,w_{12},\,w_{13}$: 사과 생산량 계산시 각 feature들(생산환경)에 곱할 가중치   <br>
$w_{21},\,w_{22},\,w_{23}$: 오렌지 생산량 계산시 각 feature들(생산환경)에 곱할 가중치    

<center>
<img src="https://raw.githubusercontent.com/kgmyhGit/image_resource/main/deeplearning/figures/3_unit_layer.png">
</center>

In [ ]:
# weight/bias 를 정의 -> 초기값은 random 값을 이용해서 생성.
weight = torch.randn(3, 2, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

weight.size(), bias.size()
# weight: (3:input feature개수  ,  2:output 개수)
# bias  : (2:output 개수, )

(torch.Size([3, 2]), torch.Size([2]))

In [ ]:
weight

tensor([[-0.2174,  0.5123],
        [ 0.3846, -0.3597],
        [-0.0671, -0.4833]], requires_grad=True)

In [ ]:
bias

tensor([-1.2495, -0.4627], requires_grad=True)

In [ ]:
X

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [ ]:
# 한번 학습(최적화)
## 추론
pred = X @ weight + bias

In [ ]:
print(pred.size())
pred

torch.Size([5, 2])


tensor([[  5.7630,  -7.9486],
        [  8.5169, -16.4304],
        [ 27.4796, -32.1259],
        [ -9.3677,  18.4393],
        [ 15.9728, -33.4773]], grad_fn=<AddBackward0>)

In [ ]:
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
## loss 계산(MSE)
loss = torch.mean((pred - y)**2) # 전체 추론한 결과의 평균오차를 계산.
loss

tensor(9543.7471, grad_fn=<MeanBackward0>)

In [ ]:
# loss를 가지고 파라미터들(weight들, bias들)의 gradient 계산.
loss.backward()

In [ ]:
weight.data

tensor([[-0.2174,  0.5123],
        [ 0.3846, -0.3597],
        [-0.0671, -0.4833]])

In [ ]:
weight.grad

tensor([[ -5485.9819,  -8631.2988],
        [ -6342.3081, -10623.8477],
        [ -3871.9595,  -6360.9590]])

In [ ]:
bias.data, bias.grad

(tensor([-1.2495, -0.4627]), tensor([ -66.5271, -106.3086]))

In [ ]:
# 파라미터 업데이트
lr = 0.00001
weight.data = weight.data - lr * weight.grad
bias.data = bias.data - lr * bias.grad

In [ ]:
weight.data

tensor([[-0.1625,  0.5986],
        [ 0.4480, -0.2535],
        [-0.0284, -0.4197]])

In [ ]:
bias.data

tensor([-1.2489, -0.4616])

In [ ]:
## 업데이트된 파라미터로 추정 -> loss 계산
pred2 = X @ weight + bias
loss2 = torch.mean((pred2 - y)**2)

In [ ]:
print(loss.item(), loss2.item())

9543.7470703125 6691.7646484375


##  모델링

In [ ]:
weight = torch.randn(3, 2, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

## 모델 정의
def model(X):
    return X @ weight + bias

## loss 함수(MSE)
def loss_fn(pred, y):
    return torch.mean((pred - y)**2) # 전체 오차의 평균.

In [ ]:
X.shape

torch.Size([5, 3])

In [ ]:
epochs = 5000
lr = 0.00001  # 1e-5
for epoch in range(epochs):
    # 1. 추론
    pred = model(X)
    
    # 2. loss 계산
    loss = loss_fn(pred, y)
    # 3. 파라미터 들의 gradient 계산
    loss.backward()
    # 4. 파라미터 업데이트
    weight.data = weight.data - lr * weight.grad
    bias.data = bias.data - lr * bias.grad
    # 5. gradient 초기화
    weight.grad = None
    bias.grad = None
    ## 100 epoch, 마지막 epoch에서 loss를 출력 => 학습 과정 log를 출력
    if epoch % 100 == 0 or epoch == epochs-1:
        print(f"[{epoch+1:04d}/{epochs}] - {loss.item():.5f}")

[0001/5000] - 21877.03516
[0101/5000] - 307.67975
[0201/5000] - 171.04639
[0301/5000] - 118.33372
[0401/5000] - 91.61832
[0501/5000] - 74.22965
[0601/5000] - 61.14329
[0701/5000] - 50.66256
[0801/5000] - 42.07299
[0901/5000] - 34.97640
[1001/5000] - 29.09731
[1101/5000] - 24.22213
[1201/5000] - 20.17823
[1301/5000] - 16.82346
[1401/5000] - 14.04033
[1501/5000] - 11.73142
[1601/5000] - 9.81581
[1701/5000] - 8.22664
[1801/5000] - 6.90820
[1901/5000] - 5.81437
[2001/5000] - 4.90693
[2101/5000] - 4.15409
[2201/5000] - 3.52951
[2301/5000] - 3.01134
[2401/5000] - 2.58146
[2501/5000] - 2.22482
[2601/5000] - 1.92892
[2701/5000] - 1.68346
[2801/5000] - 1.47981
[2901/5000] - 1.31085
[3001/5000] - 1.17069
[3101/5000] - 1.05440
[3201/5000] - 0.95793
[3301/5000] - 0.87789
[3401/5000] - 0.81149
[3501/5000] - 0.75641
[3601/5000] - 0.71071
[3701/5000] - 0.67278
[3801/5000] - 0.64133
[3901/5000] - 0.61523
[4001/5000] - 0.59358
[4101/5000] - 0.57562
[4201/5000] - 0.56071
[4301/5000] - 0.54836
[4401/5000

위 결과를 보면 처음에는 개선량이 큰데, 점점 줄어듬. 첫 값이 랜덤값이라서.

In [ ]:
(weight.data, bias.data)

(tensor([[-0.3941, -0.2769],
         [ 0.8493,  0.8004],
         [ 0.6883,  0.9120]]),
 tensor([-0.6791, -2.7750]))

In [ ]:
# 새로운 데이터로 추론
p = model(X)
p

tensor([[ 57.0546,  69.8592],
        [ 82.2513, 100.8372],
        [118.7677, 133.2930],
        [ 21.1116,  37.1464],
        [101.8461, 118.8047]], grad_fn=<AddBackward0>)

In [ ]:
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
new_x = torch.tensor([68, 82, 56], dtype=torch.float32)
new_x = new_x.unsqueeze(dim=0)
new_x.shape

torch.Size([1, 3])

In [ ]:
with torch.no_grad():
    model(new_x)
    
print(p)

tensor([[ 57.0546,  69.8592],
        [ 82.2513, 100.8372],
        [118.7677, 133.2930],
        [ 21.1116,  37.1464],
        [101.8461, 118.8047]], grad_fn=<AddBackward0>)


# pytorch built-in 모델을 사용해 Linear Regression 구현

In [ ]:
inputs = torch.tensor(
    [[73, 67, 43], 
     [91, 88, 64], 
     [87, 134, 58], 
     [102, 43, 37], 
     [69, 96, 70]], dtype=torch.float32)

In [ ]:
targets = torch.tensor(
    [[56, 70], 
    [81, 101], 
    [119, 133], 
    [22, 37], 
    [103, 119]], dtype=torch.float32)

## torch.nn.Linear
Pytorch는 torch.nn.Linear 클래스를 통해 Linear Regression 모델을 제공한다.  
torch.nn.Linear에 입력 feature의 개수와 출력 값의 개수를 지정하면 random 값으로 초기화한 weight와 bias들을 생성해 모델을 구성한다.
- `torch.nn.Linear(input feature의 개수 , output 값의 개수)`

## Optimizer와 Loss 함수 정의
- **Optimizer**: 계산된 gradient값을 이용해 파라미터들을 업데이트 하는 함수
- **Loss 함수**: 정답과 모델이 예측한 값사이의 차이(오차)를 계산하는 함수.
  - 모델을 최적화하는 것은 이 함수의 값을 최소화하는 것을 말한다. 
- `torch.optim` 모듈에 다양한 Optimizer 클래스가 구현되있다.
- `torch.nn` 또는 `torch.nn.functional` 모듈에 다양한 Loss 함수가 제공된다. 

In [3]:
# 선형회귀 모델을 정의. torch.nn.Linear 클래스
import torch
import torch.nn as nn

model = nn.Linear(3, 2)  # 3: input feature 개수, 2: output 수

OSError: [WinError 1114] DLL 초기화 루틴을 실행할 수 없습니다. Error loading "c:\Users\Playdata\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\lib\c10.dll" or one of its dependencies.

In [ ]:
model.weight

Parameter containing:
tensor([[ 0.4063,  0.4480, -0.0565],
        [ 0.3550,  0.5531,  0.5037]], requires_grad=True)

In [ ]:
model.bias

Parameter containing:
tensor([-0.2737, -0.0201], requires_grad=True)

In [ ]:
# loss 함수
loss_fn = torch.nn.MSELoss()  # 클래스
# loss_fn = torch.nn.functional.mse_loss # 함수 

In [ ]:
for a in model.parameters():
    print(a)

Parameter containing:
tensor([[ 0.4063,  0.4480, -0.0565],
        [ 0.3550,  0.5531,  0.5037]], requires_grad=True)
Parameter containing:
tensor([-0.2737, -0.0201], requires_grad=True)


In [ ]:
# optimizer (torch.optim 모듈에 정의): weight.data = weight.data - lr * weight.grad
optimizer = torch.optim.SGD(
    model.parameters(), # 최적화 대상 파라미터들을 model에서 조회해서 전달.
    lr = 0.00001,       # Learning Rage
)

In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4063,  0.4480, -0.0565],
         [ 0.3550,  0.5531,  0.5037]], requires_grad=True),
 Parameter containing:
 tensor([-0.2737, -0.0201], requires_grad=True)]

## Model Train

In [ ]:
epochs = 5000

for epoch in range(epochs):
    # 추론
    pred = model(inputs)  
    # loss 계산
    loss = loss_fn(pred, targets) # torch.nn.functional.mse_loss(pred, targets) # (모델추정값, 정답)
    # gradient 계산
    loss.backward()
    # 파라미터 업데이트: optimizer.step()
    optimizer.step() # optimizer가 weight.data = weight.data - lr * weight.grad 이걸 해줌.
    # 파라미터 초기화 
    optimizer.zero_grad() # optimizer가 w.grad=None, b.grad=None 를 해줌.
    # 현재 epoch 학습 결과를 log로 출력
    if epoch % 100 == 0 or epoch == epochs-1:
        print(f"[{epoch+1:04d}/{epochs}] - {loss.item()}")

[0001/5000] - 557.4327392578125
[0101/5000] - 143.0001220703125
[0201/5000] - 55.01811981201172
[0301/5000] - 27.855144500732422
[0401/5000] - 18.180072784423828
[0501/5000] - 13.762025833129883
[0601/5000] - 11.109319686889648
[0701/5000] - 9.192716598510742
[0801/5000] - 7.682383060455322
[0901/5000] - 6.451747894287109
[1001/5000] - 5.43704891204834
[1101/5000] - 4.597002983093262
[1201/5000] - 3.900576114654541
[1301/5000] - 3.3229355812072754
[1401/5000] - 2.843738317489624
[1501/5000] - 2.446216344833374
[1601/5000] - 2.1164069175720215
[1701/5000] - 1.8427997827529907
[1801/5000] - 1.6157970428466797
[1901/5000] - 1.4274770021438599
[2001/5000] - 1.2712451219558716
[2101/5000] - 1.1416248083114624
[2201/5000] - 1.0340931415557861
[2301/5000] - 0.9448819160461426
[2401/5000] - 0.8708664774894714
[2501/5000] - 0.8094626665115356
[2601/5000] - 0.7585242986679077
[2701/5000] - 0.7162575721740723
[2801/5000] - 0.6811956167221069
[2901/5000] - 0.6521039009094238
[3001/5000] - 0.627972

In [ ]:
# 추론 => gradient 계산을 할 필요가 없다. ==> grad_fn을 만들 필요가 없다. 그래서 torch.no_grad() 블록에서 추론 작업을 실행한다.
with torch.no_grad():
    pred = model(inputs)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
pred

tensor([[ 57.1243,  70.3083],
        [ 82.1908, 100.6456],
        [118.7946, 133.0155],
        [ 21.1137,  37.0316],
        [101.8191, 119.0809]])

In [ ]:
# 학습 로직을 함수 구현
def train(inputs, targets, epochs, model, loss_fn, optimizer):

    for epoch in range(epochs):
        # 추론
        pred = model(inputs)
        # loss 계산
        loss = loss_fn(pred, targets) # torch.nn.functional.mse_loss(pred, targets) # (모델추정값, 정답)
        # gradient 계산
        loss.backward()
        # 파라미터 업데이트: optimizer.step()
        optimizer.step()
        # 파라미터 초기화 w.grad=None, b.grad=None
        optimizer.zero_grad()
        # 현재 epoch 학습 결과를 log로 출력
        if epoch % 100 == 0 or epoch == epochs-1:
            print(f"[{epoch+1:04d}/{epochs}] - {loss.item()}")

In [ ]:
model = nn.Linear(3, 2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)

In [ ]:
train(inputs, targets, 5000, model, nn.functional.mse_loss, optimizer)